name: Deploy static content to Pages

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      HUGO_VERSION: 0.139.2
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      # BASE_URL: https://blog.f10.org # change to your own domain
      # Change to below if you are using GitHub Pages
      # BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
      BASE_URL: https://${{ github.repository_owner }}.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: custom hugo site
        run: |
          git clone https://github.com/chinobing/repo-for-generate-blog.git blog-dir
          cp -r BACKUP/* blog-dir/content/post/
          find . -type f -path './blog-dir/*' -exec ls -l {} \;
      - name: Build Hugo site
        run: |
          hugo
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
