name: Deploy static content to Pages

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      HUGO_VERSION: 0.139.2
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      # BASE_URL: https://blog.f10.org # change to your own domain
      # Change to below if you are using GitHub Pages
      # BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
      BASE_URL: https://${{ github.repository_owner }}.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Markdown files from BACKUP to content/posts
        run: |
          mkdir -p content/posts
          cp -r BACKUP/* content/posts/
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: Set custom theme
        run: |
          git clone https://github.com/WingLim/hugo-tania.git themes/hugo-tania
      - name: Delete existing config.toml
        run: |
          rm -f config.toml
      - name: Copy custom config.toml
        run: |
          cp -f config.toml .
      - name: Build Hugo site
        run: |
          hugo --theme=hugo-tania --baseURL=$BASE_URL
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
